language: objective-c
osx_image: xcode10.1

env:
   global:
   - LANG=en_US.UTF-8

   - PROJECT="FireMock.xcodeproj"
   - IOS_SCHEME="FireMock"
   - IOS_SDK=iphonesimulator12.1

   matrix:
   - DESTINATION="OS=12.1,name=iPhone 8 Plus" SDK="$IOS_SDK" SCHEME="$IOS_SCHEME" POD_LINT="YES"
   - DESTINATION="OS=12.1,name=iPhone X"  SDK="$IOS_SDK" SCHEME="$IOS_SCHEME" POD_LINT="NO"
   - DESTINATION="OS=12.1,name=iPhone XS" SDK="$IOS_SDK" SCHEME="$IOS_SCHEME" POD_LINT="NO"

script:
- set -o pipefail

- if [ $POD_LINT == "YES" ]; then
      pod lib lint --verbose;
  fi
